### ISSUE TITLE
Release into ROS

### ISSUE THREAD

**Issue by simonschmeisser** [tork-a/rqt_joint_trajectory_plot#2]
this is a really handy tool, could we release it as a ros package? If you need assistance I will have a look and figure out what steps are necessary

**Comment by longjie** [comment]
Hi, thank you for your contributing and suggestion. I will release this package after a while.
I'm a member of @tork-a which has already released several packages. Your feedback is very helpful, because I didn't even notice someone need this package :smile:

**Comment by 7675t** [comment]
Now this package is released to Kinetic.

https://github.com/tork-a/rqt_joint_trajectory_plot-release

In the next release, [it will support JointTrajectoryAction](https://github.com/tork-a/rqt_joint_trajectory_plot/pull/6), so it will be handy to check the trajectory MoveIt! produce.
