### ISSUE TITLE
Use on Indigo

### ISSUE THREAD

**Issue by gavanderhoorn** [tork-a/rqt_joint_trajectory_plot#8]
I'm not entirely sure (as I didn't test it exhaustively), but I could at least get the widget to show on Indigo (and PyQt4) by replacing:

https://github.com/tork-a/rqt_joint_trajectory_plot/blob/e6e61ac566d324ca75be3422c32d8db18527852a/src/rqt_joint_trajectory_plot/plot_widget.py#L5

with

```python
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
```

(note the `4` there).

Just an FYI.

**Comment by 7675t** [comment]
Thank you very much, @gavanderhoorn 
With your advice and #9 , I think I can release this package into Indigo.

**Comment by 7675t** [comment]
I have released this package to Indigo. We can use it in next sync.
Thanks for contribution @gavanderhoorn
